In [1]:
import numpy as np
import torch

# Creating matrices

In [3]:
arr = [[1,2], [3,4]]
np.array(arr)

array([[1, 2],
       [3, 4]])

In [5]:
torch.Tensor(arr)

tensor([[1., 2.],
        [3., 4.]])

In [8]:
torch.ones((2,2))

tensor([[1., 1.],
        [1., 1.]])

In [10]:
torch.rand(2,2)

tensor([[0.2724, 0.9797],
        [0.0442, 0.0508]])

# Seeds for reproducibility

In [12]:
np.random.seed(100)
np.random.rand(2,2)

array([[0.54340494, 0.27836939],
       [0.42451759, 0.84477613]])

In [15]:
torch.manual_seed(100)
torch.rand(2,2)

tensor([[0.1117, 0.8158],
        [0.2626, 0.4839]])

In [22]:
# To set seed for GPU
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(100)
torch.rand(2,2) #########   Check for correct syntax

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

# Numpy & Torch bridge

In [39]:
#Numpy to torch
np_array = np.random.rand(3,3)
print(np_array)

torch_tensor = torch.from_numpy(np_array)
print(torch_tensor)

print(type(torch_tensor))

[[0.85239509 0.97500649 0.88485329]
 [0.35950784 0.59885895 0.35479561]
 [0.34019022 0.17808099 0.23769421]]
tensor([[0.8524, 0.9750, 0.8849],
        [0.3595, 0.5989, 0.3548],
        [0.3402, 0.1781, 0.2377]], dtype=torch.float64)
<class 'torch.Tensor'>


In [51]:
#Numpy to torch
np_array = np.ones((3,3), dtype=np.double)
print(np_array)

torch_tensor = torch.from_numpy(np_array)
print(torch_tensor)

print(type(torch_tensor))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
<class 'torch.Tensor'>


In [54]:
#Torch to numpy
torch_tensor = torch.rand(3,3)
print(torch_tensor)
np_array = torch_tensor.numpy()
print(np_array)

tensor([[0.0169, 0.2209, 0.9535],
        [0.7064, 0.1629, 0.8902],
        [0.5163, 0.0359, 0.6476]])
[[0.01689917 0.22089463 0.95353633]
 [0.70640296 0.16287827 0.890198  ]
 [0.5162713  0.03588456 0.6476328 ]]


# Tensors on CPU & GPU

In [56]:
tensor_cpu = torch.ones(2,2)

In [58]:
# From CPU to GPU
if torch.cuda.is_available():
    tensor_cpu.cuda()

In [59]:
# From GPU to CPU
tensor_cpu.cpu()

tensor([[1., 1.],
        [1., 1.]])

# Tensor operations

In [68]:
# Tensor resizing operation
a = torch.rand(2,2)
print(a)
print(a.size())

print(a.view(4))
print(a.view(4).size())

tensor([[0.7116, 0.1157],
        [0.6574, 0.3451]])
torch.Size([2, 2])
tensor([0.7116, 0.1157, 0.6574, 0.3451])
torch.Size([4])


In [69]:
#Element wise addtion
a = torch.ones(2,2)
b = torch.ones(2,2)
c = a+b
print(c)

tensor([[2., 2.],
        [2., 2.]])


In [71]:
# Another element wise addition method
torch.add(a,b)

tensor([[2., 2.],
        [2., 2.]])

In [73]:
# Inplace addition
print(c)
print(c.add_(a))

tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])


In [79]:
#Element wise subtraction
print(c-b)
# or
print(c.sub(a))

tensor([[2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.]])


In [80]:
#Inplace subtraction
print(c)
c.sub_(a)
print(c)

tensor([[3., 3.],
        [3., 3.]])
tensor([[2., 2.],
        [2., 2.]])


In [82]:
#Multiplication
torch.mul(a,b)

tensor([[1., 1.],
        [1., 1.]])

In [84]:
#Division
torch.div(c,b)

tensor([[2., 2.],
        [2., 2.]])

In [90]:
#Tensor mean
a = torch.Tensor([1,2,3,4,5,6,7,8,9,10])
print(a)
a.mean(dim=0)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


tensor(5.5000)

In [96]:
#Tensor mean & stdev
a = torch.Tensor([[1,2,3,4,5,6,7,8,9,10], [1,2,3,4,5,6,7,8,9,10]])
print(a.size())
print(a.mean(dim=0))
print(a.mean(dim=1))

print(a.std(dim=1))

torch.Size([2, 10])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
tensor([5.5000, 5.5000])
tensor([3.0277, 3.0277])


# Variables

In [97]:
import torch
from torch.autograd import Variable

In [99]:
a = Variable(torch.ones(2,2), requires_grad=True)
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [100]:
b = Variable(torch.ones(2,2), requires_grad=True)
a+b

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)

In [101]:
torch.add(a,b)

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)

# Gradients

In [132]:
x = Variable(torch.Tensor([1,3]), requires_grad=True)
x.view(2,1)

tensor([[1.],
        [3.]], grad_fn=<ViewBackward>)

In [133]:
y = 5 *(x + 1)**2
y

tensor([20., 80.], grad_fn=<MulBackward0>)

In [138]:
o = 0.5 * torch.sum(y)
o

tensor(50., grad_fn=<MulBackward0>)

In [135]:
o.backward()

In [136]:
x.grad

tensor([10., 20.])